// @version=5
indicator( 
     title = "futures_price_alert",
     overlay = true)

// capture and format params of interest
removeTickerChars = str.contains(syminfo.ticker, "!") ? 2 : 5
ticker = str.substring(syminfo.ticker, 0, str.length(syminfo.ticker) - removeTickerChars)
price = str.format("{0, number}", math.round(close))
day_open = request.security(syminfo.tickerid, "D", open)
percent_from_day_open = str.replace(str.replace(str.format(
     "{0, number, #.#}%", math.round(((close - day_open) / day_open) * 100), 1),
     ' ', ''), 
     "0.", ".")

// build alert message string
message = ticker + ' ' + price + ', ' + percent_from_day_open

// alert on bar close
if close > 0
    alert(message, alert.freq_once_per_bar)
