//@version=6
strategy(
    "ZN • 6E • GC",
    overlay = true,
    max_bars_back = 2000,
    pyramiding = 0,
    process_orders_on_close = false,
    calc_on_every_tick = true)

// DATA
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

isZN = syminfo.root == "ZN"
isE6 = syminfo.root == "6E"
isGC = syminfo.root == "MGC"

ZN_SYMBOL = "CBOT:ZN1!"
E6_SYMBOL = "CME:6E1!"
GC_SYMBOL = "COMEX_MINI:MGC1!"

znOpen = request.security(ZN_SYMBOL, timeframe.period, open)
znHigh = request.security(ZN_SYMBOL, timeframe.period, high)

e6Tick = request.security(E6_SYMBOL, timeframe.period, syminfo.mintick)
e6Open = request.security(E6_SYMBOL, timeframe.period, open)
e6High = request.security(E6_SYMBOL, timeframe.period, high)
e6Low = request.security(E6_SYMBOL, timeframe.period, low)
e6Close = request.security(E6_SYMBOL, timeframe.period, close)

znVwap = request.security(ZN_SYMBOL, timeframe.period, ta.vwap(open))
e6Vwap = request.security(E6_SYMBOL, timeframe.period, ta.vwap(open))
gcVwap = ta.vwap(open)

// SESSION CONTROL
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// official market open for new futures session
marketOpenTime = "1800-1801"
isNewSession = not na(time(timeframe.period, marketOpenTime, "America/New_York"))

// valid trading windows
inSessionTimes = "1810-0859,0910-1659"
isInSession = not na(time(timeframe.period, inSessionTimes, "America/New_York"))

// BLEND VWAP
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

BLENDED_VWAP_MINUTES = 240

calc_blended_vwap_times(blendedVwapMinutes) =>
    totalMinutes = (18 * 60 + blendedVwapMinutes) % 1440
    endHour = int(math.floor(totalMinutes / 60))
    endMinute = totalMinutes % 60
    "1800-" + str.tostring(endHour, "00") + str.tostring(endMinute, "00")

calc_blended_vwap() =>
    current = ta.vwap(open)
    prev = ta.valuewhen(isNewSession, current[1], 0)
    sessionStartTime = ta.valuewhen(isNewSession, time, 0)
    elapsedMinutes = (time - sessionStartTime) / 60000.0
    c = math.min(1.0, elapsedMinutes / float(BLENDED_VWAP_MINUTES))
    prev + c * (current - prev)

isBlendedVwapTimes = calc_blended_vwap_times(BLENDED_VWAP_MINUTES)
isBlendedVwap = not na(time(timeframe.period, isBlendedVwapTimes, "America/New_York"))

znBlendedVwap = request.security(ZN_SYMBOL, timeframe.period, calc_blended_vwap())
e6BlendedVwap = request.security(E6_SYMBOL, timeframe.period, calc_blended_vwap())
gcBlendedVwap = request.security( GC_SYMBOL, timeframe.period, calc_blended_vwap())

// ZN
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ZN_LOOKBACK = 45

znAvg = ta.sma(ta.ema(znOpen, ZN_LOOKBACK), 5)
znSlope = znAvg - znAvg[1]

// trend
isZNsupportive = znOpen > znAvg // and znSlope > 0
isZNhostile = not isZNsupportive

// 6E
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

E6_LOOKBACK = 45

e6Avg = ta.sma(ta.ema(e6Open, E6_LOOKBACK), 5)
e6Slope = e6Avg - e6Avg[1]

// trend
isE6supportive = e6Open > e6Avg
isE6hostile = not isE6supportive

// MACRO REGIME
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

isMacroSupportive = isZNsupportive and isE6supportive
isMacroHostile = isZNhostile and isE6hostile
isMacroNuetral = not isMacroSupportive and not isMacroHostile

// GC LOGIC
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

GC_LOOKBACK = 11
GC_EARLY_ALIGNMENT_MIN_BARS  = 2
GC_EARLY_ALIGNMENT_MAX_BARS = 7

var int gcSupportiveBars = 0
var int gcHostileBars = 0

gcAvg = ta.sma(ta.ema(open, GC_LOOKBACK), 5)
gcSlope = gcAvg - gcAvg[1]

// trend
isGCsupportive = open > gcAvg
isGChostile = not isGCsupportive

// count trend bars
gcSupportiveBars := isGCsupportive ? gcSupportiveBars[1] + 1 : 0
gcHostileBars := isGChostile ? gcHostileBars[1] + 1 : 0

//
isGCsupportiveEarly = isGCsupportive and gcSupportiveBars > GC_EARLY_ALIGNMENT_MIN_BARS and GC_EARLY_ALIGNMENT_MAX_BARS >= gcSupportiveBars
isGChostileEarly = isGChostile and gcHostileBars > GC_EARLY_ALIGNMENT_MIN_BARS and GC_EARLY_ALIGNMENT_MAX_BARS >= gcHostileBars

// GC TRADE
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var bool isLongTradeActive = false
var bool isShortTradeActive = false
var float entryPrice = na
var float exitPrice = na
var float profit = na

// entry
isLongEntry =
     isInSession
     and not isLongTradeActive
     and not isShortTradeActive
     and isMacroSupportive and isMacroSupportive[1]
     and isGCsupportiveEarly

isShortEntry =
    //  false
     isInSession
     and not isLongTradeActive
     and not isShortTradeActive
     and isMacroHostile and isMacroHostile[1]
     and isGChostileEarly

if isLongEntry
    isLongTradeActive := true
    isShortTradeActive := false
    entryPrice := open

if isShortEntry
    isLongTradeActive := false
    isShortTradeActive := true
    entryPrice := open

// exit = GC loses state
isLongExit =
     isLongTradeActive
     and (
        not isInSession
        or not isMacroSupportive
        // or not isGCsupportive
     )

isShortExit =
     isShortTradeActive
     and (
        not isInSession
        or not isMacroHostile
        // or not isGChostile
     )

if isLongExit
    isLongTradeActive := false
    exitPrice := open
    profit := exitPrice - entryPrice

if isShortExit
    isShortTradeActive := false
    exitPrice := open
    profit := entryPrice - exitPrice

// strategy
if isGC and isLongEntry
    strategy.entry("long", strategy.long)
if isGC and isShortEntry
    strategy.entry("short", strategy.short)
if isGC and isLongExit
    strategy.close("long")
if isGC and isShortExit
    strategy.close("short")

// PLOT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// colors
ZN_color = color.blue
E6_color = color.purple
GC_color = color.yellow

long_color = color.blue
short_color = color.red
win_color = color.green
loss_color = color.red
session_color = color.aqua

line_color = color.white

bar_transparency = 30
signal_tranparency = 0
line_transparency = 80

// bar color
barColor =
     not isInSession ? color.new(session_color, bar_transparency) :
     isZN and isZNsupportive ? color.new(long_color, bar_transparency) :
     isZN and isZNhostile ? color.new(short_color, bar_transparency) :
     isZN ? color.new(ZN_color, bar_transparency) :
     isE6 and isE6supportive ? color.new(long_color, bar_transparency) :
     isE6 and isE6hostile ? color.new(short_color, bar_transparency) :
     isE6 ? color.new(E6_color, bar_transparency) :
    //  isGC and isMacroSupportive ? color.new(long_color, bar_transparency) :
    //  isGC and isMacroHostile ? color.new(short_color, bar_transparency) :
     isGC and isGCsupportive ? color.new(long_color, bar_transparency) :
     isGC and isGChostile ? color.new(short_color, bar_transparency) :
     isGC ? color.new(GC_color, bar_transparency) : na
barcolor(barColor)

// entry
plot(
     isGC and isLongEntry ? open : na,
     style = plot.style_circles,
     color = color.new(long_color, signal_tranparency),
     linewidth = 6)
plot(
     isGC and isShortEntry ? open : na,
     style = plot.style_circles,
     color = color.new(short_color, signal_tranparency),
     linewidth = 6)

// exit
exit_color =
     not isInSession ? color.new(session_color, signal_tranparency) :
     profit >= 0 ? color.new(win_color, signal_tranparency) :
     color.new(loss_color, signal_tranparency)

plotshape(
     isGC and (isLongExit or isShortExit) ? open : na,
     title = "Long Exit",
     style = shape.xcross,
     location = location.absolute,
     color = exit_color,
     size = size.tiny)

// averages
plot(isZN ? znAvg : na, color = color.new(line_color, line_transparency))
plot(isE6 ? e6Avg : na, color = color.new(line_color, line_transparency))
plot(isGC ? gcAvg : na, color = color.new(line_color, line_transparency))

// vwap
// plot(isZN and isBlendedVwap ? znVwap : na, color = color.new(line_color, line_transparency), style = plot.style_linebr, linewidth = 2)
// plot(isE6 and isBlendedVwap ? e6Vwap : na, color = color.new(line_color, line_transparency), style = plot.style_linebr, linewidth = 2)
// plot(isGC and isBlendedVwap ? gcVwap : na, color = color.new(line_color, line_transparency), style = plot.style_linebr, linewidth = 2)
// plot(isZN ? znBlendedVwap : na, color = color.new(line_color, line_transparency), linewidth = 2)
// plot(isE6 ? e6BlendedVwap : na, color = color.new(line_color, line_transparency), linewidth = 2)
// plot(isGC ? gcBlendedVwap : na, color = color.new(line_color, line_transparency), linewidth = 2)

// ALERT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Event • Direction/State • Context • Value

var string alertMessage = na
alertMessage := na

// macro alert can only fire once every 10 minutes
var int lastMacroAlertTime = na
macroCooldownMs = 10 * 60 * 1000
isMacroCooldownPassed = na(lastMacroAlertTime) or (time - lastMacroAlertTime >= macroCooldownMs)

formattedPrice = str.tostring(math.round_to_mintick(open), "#.00")

// calculate p&l in ticks to protect user financial implications spoken aloud
tickSize = syminfo.mintick
longTicks = math.round((open - entryPrice) / tickSize)
shortTicks = math.round((entryPrice - open) / tickSize)

// calculate percent change on ZN to match tradingview watchlist
znPrevClose = request.security(ZN_SYMBOL, "D", close[1])
znSessionPercent = (znOpen - znPrevClose) / znPrevClose * 100.0
formattedZnSessionPercent =
     znSessionPercent == 0 ? "0.00%" :
     znSessionPercent > 0 ? "+" + str.tostring(math.abs(znSessionPercent), "0.00") + "%" :
     "-" + str.tostring(math.abs(znSessionPercent), "0.00") + "%"

// macro supportive
triggerMacroSupportive =
     isGC
     and isMacroSupportive
     and not isMacroSupportive[1]
     and isMacroCooldownPassed
if triggerMacroSupportive and not barstate.isconfirmed
    if na(alertMessage)
        alertMessage := "Macro • Supportive • Treasuries " + formattedZnSessionPercent + " • Dollar weakening"
        lastMacroAlertTime := time

// macro hostile
triggerMacroHostile =
     isGC
     and isMacroHostile
     and not isMacroHostile[1]
     and isMacroCooldownPassed
if triggerMacroHostile and not barstate.isconfirmed
    if na(alertMessage)
        alertMessage := "Macro • Hostile • Treasuries " + formattedZnSessionPercent + " • Dollar strengthening"
        lastMacroAlertTime := time

// entry
if isGC and isLongEntry and not barstate.isconfirmed
    if na(alertMessage)
        alertMessage := "Entry • Long • " + formattedPrice
if isGC and isShortEntry and not barstate.isconfirmed
    if na(alertMessage)
        alertMessage := "Entry • Short • " + formattedPrice

// exit long
if isGC and isLongExit and not barstate.isconfirmed
    if na(alertMessage)
        isTreasuriesWeaker = not isZNsupportive
        isDollarStronger = not isE6supportive
        exitReason =
             isTreasuriesWeaker and not isDollarStronger ? "Treasuries weakening" :
             isDollarStronger and not isTreasuriesWeaker ? "Dollar strengtheningr" : "Macro lost"
        exitPnL =
             longTicks >= 0 ? "Plus " + str.tostring(longTicks) + " ticks" :
             "Minus " + str.tostring(math.abs(longTicks)) + " ticks"
        alertMessage := "Exit • Long • " + exitReason + " • " + exitPnL

// exit short
if isGC and isShortExit and not barstate.isconfirmed
    if na(alertMessage)
        isTreasuriesStronger = not isZNhostile
        isDollarWeaker = not isE6hostile
        exitReason =
             isTreasuriesStronger and not isDollarWeaker ? "Treasuries strengthening" :
             isDollarWeaker and not isTreasuriesStronger ? "Dollar weakening" : "Macro lost"
        exitPnL =
             shortTicks >= 0 ? "Plus " + str.tostring(shortTicks) + " ticks" :
             "Minus " + str.tostring(math.abs(shortTicks)) + " ticks"
        alertMessage := "Exit • Short • " + exitReason + " • " + exitPnL

// alert
if not na(alertMessage)
    alert(alertMessage, alert.freq_once_per_bar)