//@version=6
indicator(
    "signal",
    overlay = true,
    max_lines_count = 500,
    max_boxes_count = 500,
    max_bars_back = 2000)

// INPUT
////////////////////////////////////////////////////////////////////////////////////////////////////

CASCADE_LOOKBACK = 60
MIN_CASCADE_MOVE = 0.5
REGIME_MAX_BARS = 120

// lifecycle
var bool isCascadeActive = false
var int cascadeStartBar = na
var float cascadeHigh = na
var float cascadeLow = na
var float cascadeRange = na
var bool isTradeActive = false
var float probeLow = na
var float entryPrice = na
var int entryBar = na

// CASCADE
////////////////////////////////////////////////////////////////////////////////////////////////////

// detect cascade
avgRange = ta.sma(high - low, 20)
isLargeCascadeBar =
     (high - low) > avgRange * 2
     and (high - low) > MIN_CASCADE_MOVE
body = math.abs(close - open)
isBearBody = close < open
isLowestLow = ta.lowest(low, CASCADE_LOOKBACK) == low

triggerCascade =
     isLargeCascadeBar
     and isBearBody
     and isLowestLow

// start regime
if triggerCascade and not isCascadeActive
    isCascadeActive := true
    cascadeHigh := high
    cascadeLow := low
    cascadeRange := high - low
    cascadeStartBar := bar_index

// extend regime
triggerExtendingCascade =
     isCascadeActive
     and low < cascadeLow

// EXIT
////////////////////////////////////////////////////////////////////////////////////////////////////

triggerStopExit =
     isTradeActive
     and low < probeLow

triggerTakeProfit =
     isTradeActive
     and high > cascadeHigh

isRegimeExpired = bar_index > cascadeStartBar + REGIME_MAX_BARS
triggerExpiryExit =
     isTradeActive
     and isRegimeExpired

triggerExit =
     triggerStopExit
     or triggerTakeProfit
     or triggerExpiryExit

if triggerExit
    isTradeActive := false

isLossExit = triggerStopExit or (triggerExpiryExit and entryPrice > close)
lossExitPrice = triggerStopExit ? probeLow : close

isProfitExit = triggerTakeProfit or (triggerExpiryExit and close > entryPrice)
profitExitPrice = triggerTakeProfit ? cascadeHigh : close

// EXTEND CASCADE
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// extend regime before entry
if triggerExtendingCascade
    cascadeLow := low
    cascadeRange := cascadeHigh - cascadeLow
    isTradeActive := false

// exit with profit
if isCascadeActive and close > cascadeHigh
    isCascadeActive := false
    cascadeHigh := na
    cascadeLow := na
    cascadeRange := na

// exit due to exipry (profit or loss)
if isCascadeActive and isRegimeExpired
    isCascadeActive := false
    cascadeHigh := na
    cascadeLow := na
    cascadeRange := na

// ENTRY
////////////////////////////////////////////////////////////////////////////////////////////////////

entryLevel = (close - cascadeLow) / cascadeRange
isEntryLevelNearCascadeLow =
     entryLevel > 0
     and entryLevel < 0.2
isNotExtendingCascade = low > cascadeLow
isLargeBearBody = open > close and math.abs(close - open) / (high - low) > 0.5

triggerEntry =
     isCascadeActive
     and not isTradeActive
     and bar_index > cascadeStartBar + 1
     and isEntryLevelNearCascadeLow
     and isNotExtendingCascade
     and not isLargeBearBody

if triggerEntry
    isTradeActive := true
    probeLow := cascadeLow
    entryPrice := close
    entryBar := bar_index

// PLOT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

plotCascadeTrigger = triggerCascade
plotEntryPrice = triggerEntry ? close : na
plotCascadeHigh = isCascadeActive ? cascadeHigh : na
plotCascadeLow = isCascadeActive ? cascadeLow : na

plotshape(plotCascadeTrigger, style = shape.triangledown, location = location.abovebar, color = color.red, size = size.small)
plotshape(plotEntryPrice, style = shape.circle, location = location.absolute, color = color.blue, size = size.tiny)
plot(plotCascadeHigh, color = color.yellow, linewidth = 1, style = plot.style_linebr)
plot(plotCascadeLow, color = color.yellow, linewidth = 1, style = plot.style_linebr)

if isLossExit
    box.new(
        entryBar,
        entryPrice,
        bar_index,
        lossExitPrice,
        bgcolor = color.new(color.red, 85),
        border_color = color.new(color.red, 0))
if isProfitExit
    box.new(
        entryBar,
        entryPrice,
        bar_index,
        profitExitPrice,
        bgcolor = color.new(color.green, 85),
        border_color = color.new(color.green, 0))

// ALERT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var string alertMessage = na
alertMessage := na

if triggerCascade
    totalMovePercentText = str.tostring(math.round(((high - low) / high) * 100.0, 2)) + "%"
    alertMessage := "Downside stop cascade with " + totalMovePercentText + " move."

else if triggerEntry
    alertMessage := "Long entry at " + str.tostring(close, format.mintick) + " / oz."

else if triggerStopExit
    stopTicks = math.round((entryPrice - probeLow) / syminfo.mintick)
    alertMessage := "Stop loss " + str.tostring(stopTicks) + " ticks."

else if triggerTakeProfit
    profitTicks = math.round((cascadeHigh - entryPrice) / syminfo.mintick)
    alertMessage := "Take profit " + str.tostring(profitTicks) + " ticks."

else if triggerExpiryExit
    expiryTicks = math.round(math.abs(close - entryPrice) / syminfo.mintick)
    alertMessage :=
         close > entryPrice ?
         "Regime exhaustion exit with profit of " + str.tostring(expiryTicks) + " ticks." :
         "Regime exhaustion exit with loss of " + str.tostring(expiryTicks) + " ticks."

if not na(alertMessage)
    alert(alertMessage, alert.freq_once_per_bar_close)
