//@version=6
indicator(
    "signal engine",
    overlay = true,
    max_boxes_count = 500,
    max_bars_back = 2000)

// INPUT
////////////////////////////////////////////////////////////////////////////////////////////////////

// expansion/exhaustion
VELOCITY_BARS = 20
VELOCITY_BASELINE_BARS = 120
SMOOTH_BARS = 6
ACCELERATION_BARS = 5
ACCELERATION_PERCENT = 12.0
EXPANSION_LEVEL_PERCENT = 85
EXHAUSTION_LEVEL_PERCENT = 45
TREND_MATURE_BARS = 20
EXHAUSTION_REVERSAL_BARS = 6

// stop cascade
VELOCITY_SPIKE_RATIO = 3.6
RANGE_EXPANSION_RATIO = 3.0
BAR_STRENGTH_RATIO = 0.80
COMPRESSION_STD_DEV_PERCENT = 0.18
STOP_CASCADE_LOOKBACK = 22

// range breakout
RANGE_PERCENT = 0.22
RANGE_BARS = 120
RANGE_MOMENTUM = 25

// INIT
////////////////////////////////////////////////////////////////////////////////////////////////////

// lifecycle
var int expansionStartBar = bar_index
var float expansionStartPrice = open
var bool isExpansionActive = false
var bool isExpansionUp = false
var float expansionPeakMomentum = 0.0
var float expansionHigh = high
var float expansionLow = low
var color expansionColor = color.black
var box expansionBox = na
var bool hasActiveCascade = false
var bool isRangeActive = false
var int rangeStartBar = bar_index
var float rangeHigh = high
var float rangeLow = low

// momentum
velocity = math.abs(close - close[VELOCITY_BARS]) / VELOCITY_BARS // Δ price / time
velocitySma = nz(ta.sma(velocity, VELOCITY_BASELINE_BARS), 1) // simple moving average
rawMomentumPercent = (velocity / velocitySma - 1.0) * 100.0 // momentum = velocity / moving average
momentum = ta.sma(rawMomentumPercent, SMOOTH_BARS) // smooth

// direction
isUp = close > close[VELOCITY_BARS]
isDown = close[VELOCITY_BARS] > close

// EXPANSION (momentum increase past threshold)
////////////////////////////////////////////////////////////////////////////////////////////////////

// acceleration = Δ momentum
acceleration = momentum - momentum[ACCELERATION_BARS]
isAccelerating = acceleration > ACCELERATION_PERCENT

// expansion condition
isExpansion =
     momentum > EXPANSION_LEVEL_PERCENT
     and isAccelerating
isNewTrend =
     not isExpansionActive
     or isExpansionUp != isUp
triggerExpansion =
     isExpansion
     and isNewTrend
     and not isExpansion[1] // prevent duplicate signals on consecutive bars
     and isNewTrend[1] // prevent duplicate signals on consecutive bars

if triggerExpansion
    isExpansionActive := true
    isExpansionUp := isUp
    hasActiveCascade := false
    expansionPeakMomentum := momentum

if isExpansionActive
    expansionPeakMomentum := math.max(expansionPeakMomentum, momentum)

// plot /////////////////////////////////////////////////////////
if triggerExpansion
    expansionStartBar := bar_index
    expansionColor := isUp ? color.new(color.blue, 80) : color.new(color.red, 80)
    expansionBox := box.new(
        left = expansionStartBar,
        right = bar_index,
        top = high,
        bottom = low,
        border_color = expansionColor,
        bgcolor = expansionColor)

if isExpansionActive
    trendLength = bar_index - expansionStartBar + 1
    expansionHigh := ta.highest(high, trendLength)
    expansionLow := ta.lowest(low,  trendLength)
    box.set_right(expansionBox, bar_index)
    box.set_top(expansionBox, expansionHigh)
    box.set_bottom(expansionBox, expansionLow)

barcolor(triggerExpansion ? (isUp ? color.blue : color.red): na)

// alert ////////////////////////////////////////////////////////
formattedMomentum = str.tostring(math.round(momentum)) + "%"
isOppositeExpansion =
     triggerExpansion
     and isExpansionActive[1]
     and isUp != isExpansionUp[1]

// expansion flip (new expansion in opposite direction of active trend)
flipText = "Trend reversal, "

// new expansion (no active trend)
expansionText =
     (isUp ? "Upside " : "Downside ") +
     "expansion. Momentum " + formattedMomentum

if triggerExpansion and not barstate.isconfirmed
    alert(isOppositeExpansion ? flipText + expansionText: expansionText, alert.freq_once_per_bar)

// EXHAUSTION (trend fails to hold momentum after expansion)
////////////////////////////////////////////////////////////////////////////////////////////////////

// drop from peak
momentumDropPercent = (expansionPeakMomentum - momentum) / expansionPeakMomentum * 100.0
isMomentumDrop = momentumDropPercent > EXHAUSTION_LEVEL_PERCENT

// sustained reversal
declineCount = 0
for i = 0 to EXHAUSTION_REVERSAL_BARS
    declineCount += momentum[i + 1] > momentum[i] ? 1 : 0
isMomentumReversing = declineCount > EXHAUSTION_REVERSAL_BARS * 0.7

// ensure trend had time to develop
isTrendMature = bar_index - expansionStartBar > TREND_MATURE_BARS

triggerExhaustion =
     isExpansionActive
     and isTrendMature
     and isMomentumDrop
     and isMomentumReversing
     and isNewTrend

if triggerExhaustion
    isExpansionActive := false
    expansionPeakMomentum := 0.0
    hasActiveCascade := false

// alert ////////////////////////////////////////////////////////
trendMovePercent =
     isExpansionUp ? (expansionHigh - expansionLow) / expansionLow* 100.0 :
     (expansionHigh - expansionLow) / expansionHigh * 100.0
isTrendProfitable = trendMovePercent > 0

// only append total price move if trend profitable
formattedTrendMove = str.tostring(math.round(math.abs(trendMovePercent), 2)) + "% "
exhaustionText = (isExpansionUp ? "Upside " : "Downside ") + "exhaustion." +
     (isTrendProfitable ? " Move " + formattedTrendMove : "")
if triggerExhaustion and not barstate.isconfirmed
    alert(exhaustionText, alert.freq_once_per_bar)

// STOP CASCADE
////////////////////////////////////////////////////////////////////////////////////////////////////

// velocity spike
velocityCurrent = math.abs(close - close[1])
velocityAverage = ta.sma(velocityCurrent, 20)
isVelocitySpike = velocityCurrent > velocityAverage * VELOCITY_SPIKE_RATIO

// range expansion
barRange = high - low
rangeAvg = ta.sma(barRange, 20)
isRangeExpansion = barRange > rangeAvg * RANGE_EXPANSION_RATIO

// directional dominance
isStrongUpBar = close > open and (close - open) / barRange > BAR_STRENGTH_RATIO
isStrongDownBar = open > close and (open - close) / barRange > BAR_STRENGTH_RATIO

// compression
isCompressed = COMPRESSION_STD_DEV_PERCENT > ta.stdev(close, 20) / close * 100

// structure break
highestHigh = ta.highest(high[2], STOP_CASCADE_LOOKBACK)
lowestLow = ta.lowest(low[2], STOP_CASCADE_LOOKBACK)
isBreakUp = high > highestHigh
isBreakDown = lowestLow > low

isStopCascadeUp = isVelocitySpike and isRangeExpansion and isStrongUpBar and isCompressed and isBreakUp
isStopCascadeDown = isVelocitySpike and isRangeExpansion and isStrongDownBar and isCompressed and isBreakDown
triggerStopCascade = isStopCascadeUp or isStopCascadeDown

// allow continuation cascade
if triggerStopCascade
    hasActiveCascade := true

// plot /////////////////////////////////////////////////////////
plotshape(
     isStopCascadeUp,
     title = "up cascade",
     location = location.belowbar,
     style = shape.triangleup,
     color = color.blue,
     size = size.small)
plotshape(
     isStopCascadeDown,
     title = "down cascade",
     location = location.abovebar,
     style = shape.triangledown,
     color = color.red,
     size = size.small)

// alert ////////////////////////////////////////////////////////
cascadeText =
     (isStrongUpBar ? "Upside " : "Downside ") + "stop cascade."
if triggerStopCascade and not barstate.isconfirmed
    alert(cascadeText, alert.freq_once_per_bar)

// CONTINUATION STOP CASCADE
////////////////////////////////////////////////////////////////////////////////////////////////////

isContinuationCascadeDown =
     hasActiveCascade
     and not isExpansionUp
     and isStrongDownBar
     and isBreakDown
     and acceleration > ACCELERATION_PERCENT

isContinuationCascadeUp =
     hasActiveCascade
     and isExpansionUp
     and isStrongUpBar
     and isBreakUp
     and acceleration > ACCELERATION_PERCENT

triggerContinuationCascade =
     (isContinuationCascadeUp or isContinuationCascadeDown)
     and not triggerStopCascade // prevent overlap with initial cascade signal

// plot /////////////////////////////////////////////////////////
plotshape(
     triggerContinuationCascade and isContinuationCascadeUp,
     title = "up continuation cascade",
     location = location.belowbar,
     style = shape.diamond,
     color = color.blue,
     size = size.small)

plotshape(
     triggerContinuationCascade and isContinuationCascadeDown,
     title = "down continuation cascade",
     location = location.abovebar,
     style = shape.diamond,
     color = color.red,
     size = size.small)

// alert ////////////////////////////////////////////////////////
continuationCascadeText =
     (isContinuationCascadeUp ? "Upside " : "Downside ") +
     "cascade continuation."

if triggerContinuationCascade and not barstate.isconfirmed
    alert(continuationCascadeText, alert.freq_once_per_bar)

// RANGE BREAKOUT
////////////////////////////////////////////////////////////////////////////////////////////////////

// rolling range
rollingHigh = ta.highest(high, RANGE_BARS)
rollingLow = ta.lowest(low, RANGE_BARS)
rollingMid = (rollingHigh + rollingLow) * 0.5
rangeWidthPercent = (rollingHigh - rollingLow) / rollingMid * 100.0
isRange = RANGE_PERCENT > rangeWidthPercent

// prevent errant breakout signals
isMomentumLow = RANGE_MOMENTUM > momentum
isRangeValid =
     isMomentumLow
     and not isExpansionActive
     and not triggerStopCascade

// range start
triggerRangeStart =
     isRange
     and isRangeValid
     and not isRange[1]
     and not isRangeActive
if triggerRangeStart
    isRangeActive := true
    rangeStartBar := bar_index
    rangeHigh := rollingHigh
    rangeLow := rollingLow

// breakout
isRangeBreakoutUp = isRangeActive and high > rangeHigh
isRangeBreakoutDown = isRangeActive and rangeLow > low
triggerRangeExit = isRangeBreakoutUp or isRangeBreakoutDown
if triggerRangeExit
    isRangeActive := false

// plot /////////////////////////////////////////////////////////
if triggerRangeExit
    line.new(
             x1 = rangeStartBar - RANGE_BARS,
             y1 = (rangeHigh + rangeLow) * 0.5,
             x2 = bar_index,
             y2 = (rangeHigh + rangeLow) * 0.5,
             color = color.new(color.teal, 50),
             style = line.style_dotted,
             width = 2)

    box.new(
         left = rangeStartBar - RANGE_BARS,
         right = bar_index,
         top = rangeHigh,
         bottom = rangeLow,
         border_color = color.new(color.teal, 88),
         bgcolor = color.new(color.teal, 88))

plotshape(
     isRangeBreakoutUp,
     title = "range exit up",
     location = location.abovebar,
     style = shape.circle,
     color = color.blue,
     size = size.tiny)
plotshape(
     isRangeBreakoutDown,
     title = "range exit down",
     location = location.belowbar,
     style = shape.circle,
     color = color.red,
     size = size.tiny)

// alert ////////////////////////////////////////////////////////
rangeDuration = bar_index - rangeStartBar
rangeText = "Exiting " + str.tostring(rangeDuration) + " minute range to " +
     (isRangeBreakoutUp ? "upside" : "downside")

if triggerRangeExit and not barstate.isconfirmed
    alert(rangeText, alert.freq_once_per_bar)