# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

###############################################################

update_fastlane

lane :deploy do
  gradle(
    task: "bundle",
    build_type: "release"
  )
  upload_to_play_store(
    track: "alpha",
    in_app_update_priority: 3, # 5 -> force update
    skip_upload_apk: true,
    skip_upload_metadata: true,
    skip_upload_changelogs: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
end